# Generated by Django 4.1.3 on 2022-11-14 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
